name: Postman - Smoke (PR & Branch Push)

on:
  pull_request:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i -g newman

      - name: Create environment from template
        run: |
          cp postman/environments/dev.postman_environment.json.example dev.env.json
          sed -i "s|\"API_BASE_URL\": \"\"|\"API_BASE_URL\": \"${{ secrets.API_BASE_URL }}\"|" dev.env.json
          sed -i "s|\"Token\": \"\"|\"Token\": \"${{ secrets.Token }}\"|" dev.env.json
          sed -i "s|\"Inst_Num\": \"\"|\"Inst_Num\": \"${{ secrets.Inst_Num }}\"|" dev.env.json
          sed -i "s|\"Application_Num\": \"\"|\"Application_Num\": \"${{ secrets.Application_Num }}\"|" dev.env.json

      - name: Run Newman (SMOKE)
        run: |
          newman run postman/collections/API_Showcase_Base.postman_collection.json \
            -e dev.env.json \
            --reporters cli,junit \
            --reporter-junit-export newman-smoke.xml

      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: newman-smoke-report
          path: newman-smoke.xml
